export const defaultMissions = [
  { "name": "Logra que alguien te dé un abrazo", "type": "General" },
  { "name": "Pregunta a alguien que se ría fuerte", "type": "General" },
  { "name": "Pregunta a alguien que diga 'qué calor'", "type": "General" },
  { "name": "Logra que alguien hable sobre el clima", "type": "General" },
  { "name": "Consigue que alguien te pregunte tu edad", "type": "General" },
  { "name": "Haz que alguien te diga la hora", "type": "General" },
  { "name": "Pregunta a alguien que te cuente un secreto", "type": "General" },
  { "name": "Consigue que alguien cante una canción", "type": "General" },
  { "name": "Consigue que alguien te preste su móvil", "type": "General" },
  { "name": "Haz que alguien se quite los zapatos", "type": "General" },
  { "name": "Dile a alguien que se quite los zapatos", "type": "General" },
  { "name": "Consigue que alguien te cuente su mayor sueño", "type": "General" },
  { "name": "Logra que alguien te muestre una foto de su mascota", "type": "General" },
  { "name": "Pregunta a alguien cuál es su libro favorito", "type": "General" },
  { "name": "Consigue que alguien te diga cuál es su película favorita", "type": "General" },
  { "name": "Haz que alguien te recomiende una canción", "type": "General" },
  { "name": "Logra que alguien te diga cuál es su comida favorita", "type": "General" },
  { "name": "Pregunta a alguien cuál es su lugar favorito en el mundo", "type": "General" },
  { "name": "Consigue que alguien te cuente una anécdota divertida", "type": "General" },
  { "name": "Haz que alguien te diga qué le apasiona", "type": "General" },
  { "name": "Logra que alguien te enseñe una palabra en otro idioma", "type": "General" },
  { "name": "Pregunta a alguien cuál es su recuerdo más feliz", "type": "General" },
  { "name": "Consigue que alguien te diga qué talento secreto tiene", "type": "General" },
  { "name": "Haz que alguien te dibuje algo sencillo", "type": "General" },
  { "name": "Logra que alguien te diga cuál es su color favorito", "type": "General" },
  { "name": "Pregunta a alguien qué le gustaría aprender", "type": "General" },
  { "name": "Consigue que alguien te cuente sobre su trabajo o estudio", "type": "General" },
  { "name": "Haz que alguien te diga cuál es su estación del año favorita", "type": "General" },
  { "name": "Logra que alguien te imite a un animal", "type": "General" },
  { "name": "Pregunta a alguien cuál es su mayor logro", "type": "General" },
  { "name": "Consigue que alguien te diga qué superpoder le gustaría tener", "type": "General" },
  { "name": "Haz que alguien te cuente un chiste malo", "type": "General" },
  { "name": "Logra que alguien te diga cuál es su día de la semana favorito", "type": "General" },
  { "name": "Pregunta a alguien qué le hace feliz", "type": "General" },
  { "name": "Consigue que alguien te hable sobre un hobby", "type": "General" },
  { "name": "Haz que alguien te diga cuál es su número favorito", "type": "General" },
  { "name": "Logra que alguien te muestre algo que lleva consigo", "type": "General" },
  { "name": "Pregunta a alguien cuál es su bebida favorita", "type": "General" },
  { "name": "Consigue que alguien te cuente sobre un viaje que hizo", "type": "General" },
  { "name": "Haz que alguien te diga qué tipo de música le gusta", "type": "General" },
  { "name": "Logra que alguien te dé un cumplido sincero", "type": "General" },
  { "name": "Pregunta a alguien cuál es su asignatura favorita (si aplica)", "type": "General" },
  { "name": "Consigue que alguien te diga qué cambiaría del mundo", "type": "General" },
  { "name": "Haz que alguien te diga una frase inspiradora", "type": "General" },
  { "name": "Logra que alguien te cuente algo que le da vergüenza", "type": "General" },
  { "name": "Pregunta a alguien cuál es su postre favorito", "type": "General" },
  { "name": "Consigue que alguien te diga qué mascota le gustaría tener", "type": "General" },
  { "name": "Haz que alguien te diga el nombre de una persona que admira", "type": "General" },
  { "name": "Logra que alguien te cuente sobre una tradición familiar", "type": "General" },
  { "name": "Pregunta a alguien cuál es su tipo de película favorito", "type": "General" },
  { "name": "Consigue que alguien te diga qué objeto valora más", "type": "General" },
  { "name": "Haz que alguien te diga una noticia interesante que haya leído", "type": "General" },
  { "name": "Logra que alguien te cuente sobre un concierto o evento al que fue", "type": "General" },
  { "name": "Pregunta a alguien cuál es su marca de ropa favorita (si tiene)", "type": "General" },
  { "name": "Consigue que alguien te diga qué talento le gustaría desarrollar", "type": "General" },
  { "name": "Haz que alguien te diga el nombre de una ciudad que le gustaría visitar", "type": "General" },
  { "name": "Logra que alguien te cuente sobre una experiencia emocionante", "type": "General" },
  { "name": "Pregunta a alguien cuál es su juego de mesa o videojuego favorito", "type": "General" },
  { "name": "Consigue que alguien te diga qué invento le parece más útil", "type": "General" },
  { "name": "Haz que alguien te diga una palabra graciosa", "type": "General" },
  { "name": "Logra que alguien te cuente sobre una meta que tenga", "type": "General" },
  { "name": "Pregunta a alguien cuál es su flor favorita", "type": "General" },
  { "name": "Consigue que alguien te diga qué época histórica le interesa", "type": "General" },
  { "name": "Haz que alguien te diga el nombre de un personaje de ficción que le guste", "type": "General" },
  { "name": "Logra que alguien te cuente sobre una sorpresa que recibió o dio", "type": "General" },
  { "name": "Pregunta a alguien cuál es su tipo de arte favorito", "type": "General" },
  { "name": "Consigue que alguien te diga qué causa social le importa", "type": "General" },
  { "name": "Haz que alguien te diga una superstición que conozca", "type": "General" },
  { "name": "Logra que alguien te cuente sobre un libro que le haya marcado", "type": "General" },
  { "name": "Pregunta a alguien cuál es su animal favorito", "type": "General" },
  { "name": "Consigue que alguien te diga qué idioma le gustaría aprender", "type": "General" },
  { "name": "Haz que alguien te diga el nombre de una banda o artista musical que le guste", "type": "General" },
  { "name": "Logra que alguien te cuente sobre una celebración importante para él", "type": "General" },
  { "name": "Pregunta a alguien cuál es su tipo de programa de televisión favorito", "type": "General" },
  { "name": "Consigue que alguien te diga qué avance tecnológico le parece más impactante", "type": "General" },
  { "name": "Haz que alguien te diga una rima sencilla", "type": "General" },
  { "name": "Logra que alguien te cuente sobre un error del que aprendió", "type": "General" },
  { "name": "Pregunta a alguien cuál es su piedra preciosa favorita (si tiene)", "type": "General" },
  { "name": "Consigue que alguien te diga qué habilidad le gustaría tener", "type": "General" },
  { "name": "Haz que alguien te diga el nombre de un deportista que admire", "type": "General" },
  { "name": "Logra que alguien te cuente sobre una tradición de su cultura", "type": "General" },
  { "name": "Pregunta a alguien cuál es su tipo de coche o vehículo favorito (si tiene)", "type": "General" },
  { "name": "Consigue que alguien te diga qué problema del mundo le gustaría solucionar", "type": "General" },
  { "name": "Haz que alguien te diga un trabalenguas sencillo", "type": "General" },
  { "name": "Logra que alguien te cuente sobre un momento en el que ayudó a alguien", "type": "General" },
  { "name": "Pregunta a alguien cuál es su planeta o cuerpo celeste favorito (si tiene)", "type": "General" },
  { "name": "Consigue que alguien te diga qué regla social le parece más absurda", "type": "General" },
  { "name": "Haz que alguien te diga el nombre de un científico o inventor que admire", "type": "General" },
  { "name": "Logra que alguien te cuente sobre una costumbre extraña que tenga", "type": "General" },
  { "name": "Pregunta a alguien cuál es su tipo de clima favorito", "type": "General" },
  { "name": "Consigue que alguien te diga qué cree que pasará en el futuro", "type": "General" },
  { "name": "Haz que alguien te diga una adivinanza sencilla", "type": "General" },
  { "name": "Logra que alguien te cuente sobre un animal salvaje que haya visto", "type": "General" },
  { "name": "Pregunta a alguien cuál es su tipo de pan favorito (si tiene)", "type": "General" },
  { "name": "Consigue que alguien te diga qué tipo de vacaciones prefiere", "type": "General" },
  { "name": "Haz que alguien te diga el nombre de un monumento o lugar histórico que le guste", "type": "General" },
  { "name": "Logra que alguien te cuente sobre una experiencia que le dio miedo", "type": "General" },
  { "name": "Pregunta a alguien cuál es su tipo de salsa o condimento favorito (si tiene)", "type": "General" },
  { "name": "Consigue que alguien te diga qué objeto de su infancia recuerda con cariño", "type": "General" },
  { "name": "Haz que alguien te diga una frase hecha o refrán popular", "type": "General" },
  { "name": "Logra que alguien te cuente sobre una vez que se perdió", "type": "General" },
  { "name": "Pregunta a alguien cuál es su tipo de zapato favorito (si tiene)", "type": "General" },
  { "name": "Consigue que alguien te diga qué talento artístico le gustaría tener", "type": "General" },
  { "name": "Haz que alguien te diga el nombre de un personaje mitológico o leyenda que le guste", "type": "General" },
  { "name": "Logra que alguien te cuente sobre una travesura que hizo de niño", "type": "General" },
  { "name": "Pregunta a alguien cuál es su tipo de joya o accesorio favorito (si tiene)", "type": "General" },
  { "name": "Consigue que alguien te diga qué causa ambiental le preocupa", "type": "General" },
  { "name": "Haz que alguien te diga una onomatopeya divertida", "type": "General" },
  { "name": "Logra que alguien te cuente sobre una vez que tuvo suerte", "type": "General" },
  { "name": "Pregunta a alguien cuál es su tipo de dulce o caramelo favorito (si tiene)", "type": "General" },
  { "name": "Consigue que alguien te diga qué habilidad física le gustaría tener", "type": "General" },
  { "name": "Haz que alguien te diga el nombre de un libro de historia que le interese", "type": "General" },
  { "name": "Logra que alguien te cuente sobre una vez que hizo algo valiente", "type": "General" },
  { "name": "Pregunta a alguien cuál es su tipo de mueble favorito (si tiene)", "type": "General" },
  { "name": "Consigue que alguien te diga qué avance en la medicina le parece más importante", "type": "General" },
  { "name": "Haz que alguien te diga una exclamación sorpresa", "type": "General" },
  { "name": "Logra que alguien te cuente sobre un sueño recurrente que tenga", "type": "General" },
  { "name": "Pregunta a alguien cuál es su tipo de utensilio de cocina favorito (si tiene)", "type": "General" },
  { "name": "Consigue que alguien te diga qué tipo de energía renovable le parece más prometedora", "type": "General" },
  { "name": "Haz que alguien te diga una interjección de disgusto", "type": "General" },
  { "name": "Logra que alguien te cuente sobre una vez que se sintió muy orgulloso", "type": "General" },
  { "name": "Pregunta a alguien cuál es su tipo de electrodoméstico favorito (si tiene)", "type": "General" },
  { "name": "Consigue que alguien te diga qué tipo de transporte público usa más", "type": "General" },
  { "name": "Haz que alguien te diga una expresión de duda", "type": "General" },
  { "name": "Logra que alguien te cuente sobre una vez que hizo un regalo significativo", "type": "General" },
  { "name": "Pregunta a alguien cuál es su tipo de herramienta favorita (si tiene)", "type": "General" },
  { "name": "Consigue que alguien te diga qué tipo de construcción arquitectónica le gusta más", "type": "General" },
  { "name": "Haz que alguien te diga una negación enfática", "type": "General" },
  { "name": "Logra que alguien te cuente sobre una vez que aprendió algo importante", "type": "General" },
  { "name": "Pregunta a alguien cuál es su tipo de material textil favorito (si tiene)", "type": "General" },
  { "name": "Consigue que alguien te diga qué tipo de aplicación móvil usa más", "type": "General" },
  { "name": "Haz que alguien te diga una afirmación rotunda", "type": "General" },
  { "name": "Logra que alguien te cuente sobre una vez que superó un obstáculo", "type": "General" },
  { "name": "Pregunta a alguien cuál es su tipo de joya favorita (si tiene)", "type": "General" },
  { "name": "Consigue que alguien te diga qué tipo de red social usa más", "type": "General" },
  { "name": "Haz que alguien te diga una orden sencilla", "type": "General" },
  { "name": "Logra que alguien te cuente sobre una vez que hizo reír a alguien", "type": "General" },
  { "name": "Pregunta a alguien cuál es su tipo de calzado deportivo favorito (si tiene)", "type": "General" },
  { "name": "Consigue que alguien te diga qué tipo de contenido consume en internet", "type": "General" },
  { "name": "Haz que alguien te diga una sugerencia amable", "type": "General" },
  { "name": "Logra que alguien te cuente sobre una vez que dio un buen consejo", "type": "General" },
  { "name": "Pregunta a alguien cuál es su tipo de sombrero o gorra favorito (si tiene)", "type": "General" },
  { "name": "Consigue que alguien te diga qué tipo de evento social disfruta más", "type": "General" },
  { "name": "Haz que alguien te diga una disculpa sincera", "type": "General" },
  { "name": "Logra que alguien te cuente sobre una vez que recibió una sorpresa inesperada", "type": "General" },
  { "name": "Pregunta a alguien cuál es su tipo de instrumento musical favorito (si tiene)", "type": "General" },
  { "name": "Consigue que alguien te diga qué tipo de actividad al aire libre prefiere", "type": "General" },
  { "name": "Haz que alguien te diga un saludo informal en otro idioma", "type": "General" },
  { "name": "Logra que alguien te cuente sobre una vez que defendió a alguien", "type": "General" },
  { "name": "Pregunta a alguien cuál es su tipo de reloj favorito (si tiene)", "type": "General" },
  { "name": "Consigue que alguien te diga qué tipo de juego de mesa o cartas disfruta más", "type": "General" },
  { "name": "Haz que alguien te diga una despedida informal en otro idioma", "type": "General" },
  { "name": "Simula un estornudo muy falso y exagerado", "type": "General" },
  { "name": "Pregunta a alguien si ha notado un olor raro (sin que haya ninguno)", "type": "General" },
  { "name": "Intenta convencer a alguien de que tienes un amigo invisible muy peculiar", "type": "General" },
  { "name": "Haz como si te tropezaras con el aire", "type": "General" },
  { "name": "Pregunta a alguien cuál es su peor pesadilla (con cara de preocupación)", "type": "General" },
  { "name": "Susurra algo ininteligible a alguien y luego actúa normal", "type": "General" },
  { "name": "Intenta venderle a alguien una piedra como si fuera un objeto mágico", "type": "General" },
  { "name": "Haz una pregunta sobre algo obvio como si no tuvieras ni idea", "type": "General" },
  { "name": "Imita el sonido de un animal común en un lugar inesperado", "type": "General" },
  { "name": "Pregunta a alguien si cree en extraterrestres y defiende una teoría alocada", "type": "General" },
  { "name": "Actúa como si estuvieras buscando algo perdido urgentemente (sin buscar nada en realidad)", "type": "General" },
  { "name": "Pregunta a alguien cuál es la cosa más rara que ha visto hoy", "type": "General" },
  { "name": "Intenta hablar con alguien usando solo gestos durante un minuto", "type": "General" },
  { "name": "Pregunta a alguien si escucha un zumbido (aunque no haya ninguno)", "type": "General" },
  { "name": "Haz como si tuvieras hipo de forma muy exagerada", "type": "General" },
  { "name": "Pregunta a alguien cuál es su mayor miedo irracional", "type": "General" },
  { "name": "Empieza a tararear una canción sin motivo aparente y luego cállate de repente", "type": "General" },
  { "name": "Intenta convencer a alguien de que puedes predecir el futuro de forma extraña", "type": "General" },
  { "name": "Pregunta a alguien si ha visto un unicornio últimamente (con seriedad)", "type": "General" },
  { "name": "Actúa como si estuvieras hablando por un teléfono invisible", "type": "General" },
  { "name": "Pregunta a alguien si siente que el suelo vibra ligeramente", "type": "General" },
  { "name": "Haz como si te picara algo en un lugar extraño y sobarte discretamente", "type": "General" },
  { "name": "Intenta venderle a alguien una idea completamente absurda como si fuera genial", "type": "General" },
  { "name": "Pregunta a alguien cuál es su recuerdo más embarazoso", "type": "General" },
  { "name": "Empieza a reírte solo/a sin motivo y luego deja de golpe", "type": "General" },
  { "name": "Actúa como si estuvieras evitando una mancha invisible en el suelo", "type": "General" },
  { "name": "Pregunta a alguien si cree en fantasmas y cuenta una historia inventada", "type": "General" },
  { "name": "Haz como si se te hubiera olvidado algo muy importante de repente", "type": "General" },
  { "name": "Pregunta a alguien si ha visto un gato volador", "type": "General" },
  { "name": "Intenta imitar el sonido de una fotocopiadora o impresora", "type": "General" },
  { "name": "Pregunta a alguien si nota un cambio en la presión del aire", "type": "General" },
  { "name": "Haz como si estuvieras a punto de caerte pero te recuperas milagrosamente", "type": "General" },
  { "name": "Intenta convencer a alguien de que eres un viajero del tiempo", "type": "General" },
  { "name": "Pregunta a alguien cuál es el objeto más raro que posee", "type": "General" },
  { "name": "Empieza a aplaudir lentamente sin mirar a nadie en particular", "type": "General" },
  { "name": "Actúa como si estuvieras leyendo algo invisible en tu mano", "type": "General" },
  { "name": "Pregunta a alguien si ha soñado algo extraño anoche", "type": "General" },
  { "name": "Intenta imitar el sonido de una puerta chirriando", "type": "General" },
  { "name": "Pregunta a alguien si siente una corriente de aire frío repentina", "type": "General" },
  { "name": "Haz como si estuvieras buscando tus gafas aunque no las necesites", "type": "General" },
  { "name": "Intenta convencer a alguien de que puedes hablar con los animales", "type": "General" },
  { "name": "Pregunta a alguien cuál es su mayor arrepentimiento (con dramatismo)", "type": "General" },
  { "name": "Empieza a silbar una melodía pegadiza y luego olvida cómo sigue", "type": "General" },
  { "name": "Actúa como si estuvieras intentando recordar una palabra muy importante", "type": "General" },
  { "name": "Pregunta a alguien si ha visto tu 'aura' hoy", "type": "General" },
  { "name": "Intenta imitar el sonido de una notificación de móvil antigua", "type": "General" },
  { "name": "Pregunta a alguien si nota un sabor metálico en el ambiente", "type": "General" },
  { "name": "Haz como si estuvieras a punto de revelar un gran secreto pero te callas", "type": "General" },
  { "name": "Intenta convencer a alguien de que tienes poderes psíquicos menores", "type": "General" },
  { "name": "Pregunta a alguien cuál es su peor hábito (con curiosidad)", "type": "General" },
  { "name": "Pide a alguien que te dibuje cómo se siente en este momento", "type": "General" },
  { "name": "Logra que alguien te diga una frase improvisada como si fuera un poema", "type": "General" },
  { "name": "Consigue que alguien te haga una escultura sencilla con objetos cercanos", "type": "General" },
  { "name": "Pide a alguien que te describa un color sin usar su nombre", "type": "General" },
  { "name": "Logra que alguien te cante un fragmento de una canción inventada", "type": "General" },
  { "name": "Consigue que alguien te diga el título de una película que nunca existió", "type": "General" },
  { "name": "Pide a alguien que te haga un origami sencillo", "type": "General" },
  { "name": "Logra que alguien te cuente una historia muy corta con solo tres palabras", "type": "General" },
  { "name": "Consigue que alguien te imite una obra de arte famosa", "type": "General" },
  { "name": "Pide a alguien que te diga un eslogan para un producto imaginario", "type": "General" },
  { "name": "Haz que alguien imite la caminata de un pingüino", "type": "General" },
  { "name": "Logra que alguien imite el sonido de un electrodoméstico averiado", "type": "General" },
  { "name": "Consigue que alguien haga una pose graciosa como si fuera una estatua", "type": "General" },
  { "name": "Haz que alguien imite el movimiento de un árbol con el viento", "type": "General" },
  { "name": "Logra que alguien imite la forma de andar de un personaje famoso", "type": "General" },
  { "name": "Consigue que alguien imite el sonido de un instrumento musical sin usar la voz", "type": "General" },
  { "name": "Haz que alguien intente tocarse la nariz con la lengua (si puede o simulándolo)", "type": "General" },
  { "name": "Logra que alguien imite la reacción de sorpresa exagerada", "type": "General" },
  { "name": "Consigue que alguien haga el movimiento de remar estando de pie", "type": "General" },
  { "name": "Haz que alguien imite la forma de beber de un animal", "type": "General" },
  { "name": "Pide a alguien que te ayude a alcanzar algo que está fuera de tu alcance (aunque no lo esté realmente)", "type": "General" },
  { "name": "Logra que alguien te dé un consejo sobre un 'problema' trivial", "type": "General" },
  { "name": "Consigue que alguien te sostenga algo ligero durante un momento", "type": "General" },
  { "name": "Pide a alguien que te abra una puerta (aunque esté abierta)", "type": "General" },
  { "name": "Logra que alguien te diga cómo atar un tipo de nudo sencillo (simulando que no sabes)", "type": "General" },
  { "name": "Consigue que alguien te explique algo muy básico como si no lo entendieras", "type": "General" },
  { "name": "Pide a alguien que te preste un bolígrafo (aunque tengas uno)", "type": "General" },
  { "name": "Logra que alguien te diga la hora aunque tenga el móvil guardado", "type": "General" },
  { "name": "Consigue que alguien te indique una dirección aunque sepas dónde ir", "type": "General" },
  { "name": "Pide a alguien que te ayude a buscar algo que tienes justo delante", "type": "General" },
  { "name": "Pregunta a alguien si prefiere el helado de chocolate o vainilla (y defiende tu opción con pasión)", "type": "General" },
  { "name": "Logra que alguien te diga qué piensa sobre la forma de las nubes hoy", "type": "General" },
  { "name": "Consigue que alguien elija entre dos objetos cotidianos cuál es 'mejor' y por qué", "type": "General" },
  { "name": "Pregunta a alguien si es mejor el día o la noche (y argumenta tu postura)", "type": "General" },
  { "name": "Logra que alguien te diga qué opina sobre llevar calcetines con sandalias", "type": "General" },
  { "name": "Consigue que alguien elija entre el café y el té y explique su preferencia", "type": "General" },
  { "name": "Pregunta a alguien si prefiere los perros o los gatos (y defiende tu elección)", "type": "General" },
  { "name": "Logra que alguien te diga qué piensa sobre los emojis en las conversaciones serias", "type": "General" },
  { "name": "Consigue que alguien elija entre leer un libro o ver una película y explique por qué", "type": "General" },
  { "name": "Pregunta a alguien si es mejor el verano o el invierno (y defiende tu opinión)", "type": "General" },
  { "name": "Pide a alguien que juegue 'piedra, papel o tijera' contigo", "type": "General" },
  { "name": "Logra que alguien intente adivinar cuántos dedos estás mostrando a tu espalda", "type": "General" },
  { "name": "Consigue que alguien te diga rápidamente tres palabras que rimen con una palabra que elijas", "type": "General" },
  { "name": "Pide a alguien que te diga el abecedario al revés lo más rápido posible (o intente)", "type": "General" },
  { "name": "Logra que alguien juegue a 'cara o cruz' contigo usando una moneda imaginaria", "type": "General" },
  { "name": "Consigue que alguien intente decir un trabalenguas sencillo lo más rápido posible", "type": "General" },
  { "name": "Pide a alguien que adivine un número del 1 al 10 que estás pensando", "type": "General" },
  { "name": "Logra que alguien juegue a 'veo veo' contigo (elige algo obvio)", "type": "General" },
  { "name": "Haz que alguien se tome un chupito contigo.", "type": "Fiesta" },
  { "name": "Haz que alguien haga un 'hidalgo' (beber directamente de la botella sin tocarla).", "type": "Fiesta" },
  { "name": "Haz que alguien te invite a una cerveza.", "type": "Fiesta" },
  { "name": "Haz que alguien baile contigo una coreografía inventada.", "type": "Fiesta" },
  { "name": "Logra que alguien te cuente su peor resaca.", "type": "Fiesta" },
  { "name": "Pregunta a alguien cuál es su cóctel favorito de la noche.", "type": "Fiesta" },
  { "name": "Consigue que alguien choque su vaso contigo y diga '¡Salud!' en otro idioma.", "type": "Fiesta" },
  { "name": "Haz que alguien te ofrezca probar su bebida.", "type": "Fiesta" },
  { "name": "Logra que alguien te diga el nombre de la canción que está bailando.", "type": "Fiesta" },
  { "name": "Pregunta a alguien si prefiere la cerveza, el vino o los cócteles.", "type": "Fiesta" },
  { "name": "Consigue que alguien te cuente por qué está celebrando.", "type": "Fiesta" },
  { "name": "Haz que alguien te diga un brindis divertido.", "type": "Fiesta" },
  { "name": "Logra que alguien baile contigo una canción lenta.", "type": "Fiesta" },
  { "name": "Pregunta a alguien si ha perdido algo ya esta noche.", "type": "Fiesta" },
  { "name": "Consigue que alguien te confiese su 'copa de más' de la noche.", "type": "Fiesta" },
  { "name": "Haz que alguien te cuente un chiste malo sobre borrachos.", "type": "Fiesta" },
  { "name": "Logra que alguien te siga el ritmo en una canción que tarareas.", "type": "Fiesta" },
  { "name": "Pregunta a alguien si recuerda cómo llegó a la fiesta.", "type": "Fiesta" },
  { "name": "Consigue que alguien te diga cuál es su 'yo borracho'.", "type": "Fiesta" },
  { "name": "Haz que alguien te imite a otro asistente de la fiesta (discretamente).", "type": "Fiesta" },
  { "name": "Logra que alguien te invite a bailar (sin que tú lo pidas directamente).", "type": "Fiesta" },
  { "name": "Pregunta a alguien si cree en el amor a primera vista en una fiesta.", "type": "Fiesta" },
  { "name": "Consigue que alguien te cuente un secreto 'de borrachos'.", "type": "Fiesta" },
  { "name": "Haz que alguien te dibuje algo en una servilleta después de unas copas.", "type": "Fiesta" },
  { "name": "Logra que alguien te dé su número de teléfono al final de una conversación.", "type": "Fiesta" },
  { "name": "Pregunta a alguien cuál es la cosa más loca que ha hecho en una fiesta.", "type": "Fiesta" },
  { "name": "Consigue que alguien baile de forma ridícula contigo sin importarle nada.", "type": "Fiesta" },
  { "name": "Haz que alguien te confiese quién le atrae en la fiesta.", "type": "Fiesta" },
  { "name": "Logra que alguien te ofrezca llevarte a casa (si aplica y es seguro).", "type": "Fiesta" },
  { "name": "Pregunta a alguien si tiene algún 'talento oculto' que salga a relucir con la fiesta.", "type": "Fiesta" },
  { "name": "Consigue que alguien te abrace efusivamente y te diga que eres genial.", "type": "Fiesta" },
  { "name": "Haz que alguien te cuente una historia vergonzosa que le pasó en una fiesta.", "type": "Fiesta" },
  { "name": "Logra que alguien te diga cuál es la peor canción que han puesto esta noche.", "type": "Fiesta" },
  { "name": "Pregunta a alguien si ha bebido algo raro alguna vez en una fiesta.", "type": "Fiesta" },
  { "name": "Consigue que alguien te proponga un juego de beber sencillo.", "type": "Fiesta" },
  { "name": "Haz que alguien te dedique una canción que esté sonando.", "type": "Fiesta" },
  { "name": "Logra que alguien te siga en una coreografía sencilla que improvisas.", "type": "Fiesta" },
  { "name": "Pregunta a alguien si tiene alguna superstición sobre las fiestas.", "type": "Fiesta" },
  { "name": "Consigue que alguien te cuente sobre la mejor fiesta a la que ha ido.", "type": "Fiesta" },
  { "name": "Haz que alguien te diga qué piensa de la música del DJ (si hay).", "type": "Fiesta" },
  { "name": "Logra que alguien te ofrezca comida o snacks si hay.", "type": "Fiesta" },
  { "name": "Pregunta a alguien si prefiere las fiestas grandes o pequeñas.", "type": "Fiesta" },
  { "name": "Consigue que alguien te diga cuál es su peor recuerdo de una fiesta.", "type": "Fiesta" },
  { "name": "Haz que alguien te pida un consejo sobre algo que le pasó en la fiesta.", "type": "Fiesta" },
  { "name": "Logra que alguien te presente a otro asistente de la fiesta.", "type": "Fiesta" },
  { "name": "Pregunta a alguien si ha tenido alguna experiencia paranormal en una fiesta (bromeando).", "type": "Fiesta" },
  { "name": "Consigue que alguien te diga qué es lo más divertido que ha visto esta noche.", "type": "Fiesta" },
  { "name": "Haz que alguien te cuente sobre un disfraz memorable que usó en una fiesta (si aplica).", "type": "Fiesta" },
  { "name": "Logra que alguien te diga cuál es su canción 'de fiesta' favorita.", "type": "Fiesta" },
  { "name": "Pregunta a alguien si suele bailar mucho en las fiestas.", "type": "Fiesta" },
  { "name": "Consigue que alguien te diga qué piensa de la decoración de la fiesta.", "type": "Fiesta" },
  { "name": "Haz que alguien te cuente sobre una vez que se quedó dormido/a en una fiesta.", "type": "Fiesta" },
  { "name": "Logra que alguien te diga cuál es la bebida más rara que ha probado.", "type": "Fiesta" },
  { "name": "Pregunta a alguien si prefiere las fiestas temáticas o las normales.", "type": "Fiesta" },
  { "name": "Consigue que alguien te diga qué es lo más vergonzoso que ha hecho borracho/a.", "type": "Fiesta" },
  { "name": "Haz que alguien te pida que le guardes su bebida un momento.", "type": "Fiesta" },
  { "name": "Logra que alguien te cuente sobre una vez que conoció a alguien interesante en una fiesta.", "type": "Fiesta" },
  { "name": "Pregunta a alguien si cree que las fiestas son una buena forma de conocer gente.", "type": "Fiesta" },
  { "name": "Consigue que alguien te diga qué piensa sobre los karaokes en las fiestas.", "type": "Fiesta" },
  { "name": "Haz que alguien te cuente sobre un 'ligue' fallido en una fiesta.", "type": "Fiesta" },
  { "name": "Logra que alguien te diga cuál es su límite de alcohol.", "type": "Fiesta" },
  { "name": "Pregunta a alguien si suele beber mucho en las fiestas.", "type": "Fiesta" },
  { "name": "Consigue que alguien te diga qué piensa sobre los juegos de mesa en las fiestas.", "type": "Fiesta" },
  { "name": "Haz que alguien te cuente sobre la peor pelea que ha visto en una fiesta.", "type": "Fiesta" },
  { "name": "Logra que alguien te diga cuál es su peor excusa para no beber.", "type": "Fiesta" },
  { "name": "Pregunta a alguien si prefiere las fiestas en casa o en locales.", "type": "Fiesta" },
  { "name": "Consigue que alguien te diga qué piensa sobre la comida rápida después de una fiesta.", "type": "Fiesta" },
  { "name": "Haz que alguien te pida ayuda para encontrar algo (llaves, móvil, etc.).", "type": "Fiesta" },
  { "name": "Logra que alguien te cuente sobre una vez que se coló en una fiesta.", "type": "Fiesta" },
  { "name": "Pregunta a alguien si cree en las leyendas urbanas sobre fiestas.", "type": "Fiesta" },
  { "name": "Consigue que alguien te diga qué piensa sobre los discursos en las fiestas (ej. bodas).", "type": "Fiesta" },
  { "name": "Haz que alguien te cuente sobre la resaca más épica de un amigo/a.", "type": "Fiesta" },
  { "name": "Logra que alguien te diga cuál es su bebida 'para olvidar' favorita.", "type": "Fiesta" },
  { "name": "Pregunta a alguien si suele hacer promesas que no recuerda al día siguiente.", "type": "Fiesta" },
  { "name": "Consigue que alguien te diga qué piensa sobre las luces de la fiesta.", "type": "Fiesta" },
  { "name": "Haz que alguien te pida que le recuerdes algo importante al final de la noche.", "type": "Fiesta" },
  { "name": "Logra que alguien te cuente sobre una vez que se enamoró en una fiesta.", "type": "Fiesta" },
  { "name": "Pregunta a alguien si cree que las fiestas son necesarias.", "type": "Fiesta" },
  { "name": "Consigue que alguien te diga qué piensa sobre los fotomatones en las fiestas.", "type": "Fiesta" },
  { "name": "Haz que alguien te cuente sobre el peor 'canto de borrachos' que ha escuchado.", "type": "Fiesta" },
  { "name": "Logra que alguien te diga cuál es su bebida 'para empezar la noche' favorita.", "type": "Fiesta" },
  { "name": "Pregunta a alguien si suele arrepentirse de algo después de una fiesta.", "type": "Fiesta" },
  { "name": "Consigue que alguien te diga qué piensa sobre los juegos con alcohol.", "type": "Fiesta" },
  { "name": "Haz que alguien te cuente sobre una vez que se escondió en una fiesta.", "type": "Fiesta" },
  { "name": "Logra que alguien te diga cuál es su peor excusa para irse temprano de una fiesta.", "type": "Fiesta" },
  { "name": "Pregunta a alguien si prefiere las fiestas sorpresa o las planeadas.", "type": "Fiesta" },
  { "name": "Consigue que alguien te diga qué piensa sobre la comida casera en las fiestas.", "type": "Fiesta" },
  { "name": "Haz que alguien te pida que le presentes a alguien.", "type": "Fiesta" },
  { "name": "Logra que alguien te cuente sobre una vez que se emborrachó sin querer.", "type": "Fiesta" },
  { "name": "Pregunta a alguien si cree que las fiestas cambian a las personas.", "type": "Fiesta" },
  { "name": "Consigue que alguien te diga qué piensa sobre los bailes grupales en las fiestas.", "type": "Fiesta" },
  { "name": "Haz que alguien te cuente sobre el regalo más raro que ha recibido en una fiesta.", "type": "Fiesta" },
  { "name": "Logra que alguien te diga cuál es su bebida 'para la bajona' después de la fiesta.", "type": "Fiesta" },
  { "name": "Pregunta a alguien si suele tener 'apagones' en las fiestas.", "type": "Fiesta" },
  { "name": "Consigue que alguien te diga qué piensa sobre los disfraces improvisados en las fiestas.", "type": "Fiesta" },
  { "name": "Haz que alguien te cuente sobre la peor decisión que ha tomado borracho/a en una fiesta.", "type": "Fiesta" },
  { "name": "Logra que alguien te diga cuál es su peor 'canción de karaoke borracho' que ha cantado.", "type": "Fiesta" },
  { "name": "Pregunta a alguien si prefiere las fiestas con mucha gente o pocas.", "type": "Fiesta" },
  { "name": "Consigue que alguien te diga qué piensa sobre los juegos de cartas en las fiestas.", "type": "Fiesta" },
  { "name": "Haz que alguien te cuente sobre una vez que se cayó en una fiesta.", "type": "Fiesta" },
  { "name": "Logra que alguien te diga cuál es su peor 'intento de ligue borracho'.", "type": "Fiesta" },
  { "name": "Pregunta a alguien si suele tener 'amigos de fiesta' que no ve fuera de ellas.", "type": "Fiesta" },
  { "name": "Consigue que alguien te diga qué piensa sobre los bailes lentos en las fiestas.", "type": "Fiesta" },
  { "name": "Haz que alguien te cuente sobre el momento más embarazoso que ha vivido en una fiesta.", "type": "Fiesta" },
  { "name": "Haz que alguien te dé un beso en el cuello.", "type": "Picante" },
  { "name": "Logra que alguien te acaricie la espalda baja.", "type": "Picante" },
  { "name": "Consigue que alguien te bese la mano de forma sensual.", "type": "Picante" },
  { "name": "Haz que alguien te diga lo primero que pensó al verte.", "type": "Picante" },
  { "name": "Logra que alguien te invite a su casa 'para seguir la fiesta'.", "type": "Picante" },
  { "name": "Pregunta a alguien cuál es su mayor 'fetiche' (de forma discreta).", "type": "Picante" },
  { "name": "Consigue que alguien te abrace apretadamente y te susurre algo 'travieso'.", "type": "Picante" },
  { "name": "Haz que alguien te haga un cumplido sobre una parte específica de tu cuerpo.", "type": "Picante" },
  { "name": "Logra que alguien te cuente una fantasía erótica (sin detalles explícitos).", "type": "Picante" },
  { "name": "Pregunta a alguien qué le enciende de una persona.", "type": "Picante" },
  { "name": "Consigue que alguien te bese cerca de los labios, sin llegar a hacerlo.", "type": "Picante" },
  { "name": "Haz que alguien te diga una 'línea' que usaría para ligar contigo.", "type": "Picante" },
  { "name": "Logra que alguien te toque el pelo de forma insinuante.", "type": "Picante" },
  { "name": "Pregunta a alguien si cree en la atracción instantánea y si la siente ahora.", "type": "Picante" },
  { "name": "Consigue que alguien te ofrezca un masaje en un lugar más privado.", "type": "Picante" },
  { "name": "Haz que alguien te haga una pregunta muy personal sobre tu vida sexual.", "type": "Picante" },
  { "name": "Logra que alguien te diga qué ropa interior lleva (sin que la muestre).", "type": "Picante" },
  { "name": "Pregunta a alguien cuál ha sido su encuentro más apasionado.", "type": "Picante" },
  { "name": "Consigue que alguien te baile muy cerca, rozándote.", "type": "Picante" },
  { "name": "Haz que alguien te describa su tipo ideal físicamente (dando a entender que te describe).", "type": "Picante" },
  { "name": "Logra que alguien te pida que le cuentes una fantasía tuya.", "type": "Picante" },
  { "name": "Pregunta a alguien si prefiere dar o recibir.", "type": "Picante" },
  { "name": "Consigue que alguien te quite o te ponga una prenda de vestir (ej. chaqueta, collar) de forma lenta y con contacto.", "type": "Picante" },
  { "name": "Haz que alguien te diga algo que le provoca un escalofrío.", "type": "Picante" },
  { "name": "Logra que alguien te pregunte si estás soltero/a y si te interesa alguien en el lugar.", "type": "Picante" },
  { "name": "Pregunta a alguien cuál es su 'zona erógena' más sensible (sin ser explícito).", "type": "Picante" },
  { "name": "Consigue que alguien te bese la oreja suavemente.", "type": "Picante" },
  { "name": "Haz que alguien te haga una insinuación sobre lo que le gustaría hacer contigo.", "type": "Picante" },
  { "name": "Logra que alguien te cuente un sueño erótico reciente.", "type": "Picante" },
  { "name": "Pregunta a alguien si cree en el 'sexting' o lo ha practicado.", "type": "Picante" },
  { "name": "Consigue que alguien te rodee la cintura con sus brazos y te acerque.", "type": "Picante" },
  { "name": "Haz que alguien te diga algo que le excita de tu personalidad.", "type": "Picante" },
  { "name": "Logra que alguien te invite a compartir una bebida de forma muy íntima (bebiendo del mismo vaso a la vez).", "type": "Picante" },
  { "name": "Pregunta a alguien si alguna vez ha tenido un 'flechazo' muy fuerte.", "type": "Picante" },
  { "name": "Consigue que alguien te acaricie el muslo por un instante.", "type": "Picante" },
  { "name": "Haz que alguien te describa una situación 'hot' que imaginó contigo.", "type": "Picante" },
  { "name": "Logra que alguien te pregunte sobre tus 'líneas rojas'.", "type": "Picante" },
  { "name": "Pregunta a alguien cuál es su idea de una cita perfecta.", "type": "Picante" },
  { "name": "Consigue que alguien te dé un beso en la comisura de los labios.", "type": "Picante" },
  { "name": "Haz que alguien te diga algo que le hace perder la compostura.", "type": "Picante" },
  { "name": "Logra que alguien te invite a ver una película en un ambiente oscuro y privado.", "type": "Picante" },
  { "name": "Pregunta a alguien si cree que la atracción física es más importante que la mental.", "type": "Picante" },
  { "name": "Consigue que alguien te susurre un cumplido sobre tu cuerpo.", "type": "Picante" },
  { "name": "Haz que alguien te haga una pregunta sobre tus experiencias íntimas pasadas.", "type": "Picante" },
  { "name": "Logra que alguien te diga qué parte de tu cuerpo le atrae más.", "type": "Picante" },
  { "name": "Pregunta a alguien si alguna vez ha tenido una aventura de una noche.", "type": "Picante" },
  { "name": "Consigue que alguien te coja de la mano y te lleve a otro lugar más apartado.", "type": "Picante" },
  { "name": "Haz que alguien te diga algo que le pone 'caliente'.", "type": "Picante" },
  { "name": "Logra que alguien te pregunte qué buscas en una relación íntima.", "type": "Picante" }
  ]